server.port=8084
spring.application.name=solver-service

# Database (though solver is mostly stateless, keep for safety)
spring.datasource.url=jdbc:postgresql://localhost:5432/solver_db
spring.datasource.username=postgres
spring.datasource.password=Dilip@1248
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Master data service URL
master.data.service.url=http://localhost:8082

# Timetable service URL
timetable.service.url=http://localhost:8083