# Server
server.port=8083
spring.application.name=timetable-service

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/timetable_db
spring.datasource.username=postgres
spring.datasource.password=Dilip@1248
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Logging
logging.level.org.hibernate.SQL=DEBUG